# Generated by Django 4.1.3 on 2022-11-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApplication', '0005_hotelreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HotelApplication.hotel'),
            preserve_default=False,
        ),
    ]
