# Generated by Django 4.1.3 on 2022-11-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApplication', '0006_remove_hotel_review_review_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='hotel',
            new_name='hotels',
        ),
    ]
