# Generated by Django 4.1.3 on 2022-11-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApplication', '0007_rename_hotel_review_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='HotelApplication.hotel'),
        ),
    ]
