# Generated by Django 4.1.3 on 2022-11-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApplication', '0009_alter_review_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_review', to='HotelApplication.hotel'),
        ),
    ]
