# Generated by Django 4.1.3 on 2022-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApplication', '0012_remove_hotel_favourite_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel_rating',
            field=models.IntegerField(default=1),
        ),
    ]
