# Generated by Django 4.1.3 on 2022-11-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApplication', '0014_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotel_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
