# Generated by Django 4.1.3 on 2022-11-30 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelApplication', '0015_alter_review_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
